### PR TITLE
Provide tau constant, include unicode aliases in spec

### PR DESCRIPTION
**Pull request by Juerd**

### CODE REVIEW

**Comment by Juerd** [comment]
Related pull requests:

https://github.com/perl6/roast/pull/81
https://github.com/rakudo/rakudo/pull/614

**Comment by moritz** [comment]
In my 5 years career as a physicist I never once encountered Tau in the real world, so I'd rather see this done in a module than in core Perl 6.

**Comment by Juerd** [comment]
A module to provide 1 constant seems overkill.

The argument of not having seen it in the wild is a very weak one. Perl 6 includes a lot of new things that you probably haven't seen in the wild before Perl 6 started providing them.

**Comment by moritz** [comment]
Well, the stuff that Perl 6 provides and that I haven't seen in the wild isn't trivially composable from the usual components.

**Comment by zoffixznet** [comment]
> I'd rather see this done in a module than in core Perl 6. 

It already exists too: http://modules.perl6.org/repo/Math::Tau

**Comment by colomon** [comment]
On Thu, Dec 3, 2015 at 10:28 AM, Juerd Waalboer <notifications@github.com>
wrote:

> A module to provide 1 constant seems overkill.
>
That would seem to argue Perl 6 should include every possible constant
anyone might be interested in.  Which is a pretty daft notion, IMO.

If having a super short module is too much for you to contemplate, how
about creating Math::Constants and including a few other interesting
constants with it?

-- 
Solomon Foster: colomon@gmail.com
HarmonyWare, Inc: http://www.harmonyware.com

**Comment by Juerd** [comment]
Yes, including every possible constant would indeed be a pretty daft notion. Note that this patch is not about every possible constant, it is about a single one (and the unicode equivalents of tau and pi).

**Comment by coke** [comment]
FYI, π is already available:

11:57 < [Coke]> m: say π
11:57 < camelia> rakudo-moar 09a3e3: OUTPUT«3.14159265358979␤»

On Thu, Dec 3, 2015 at 10:46 AM, Juerd Waalboer <notifications@github.com>
wrote:

> Yes, including every possible constant would indeed be a pretty daft
> notion. Note that this patch is not about every possible constant, it is
> about a single one (and the unicode equivalents of tau and pi).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/perl6/specs/pull/103#issuecomment-161682219>.
>



-- 
Will "Coke" Coleda

**Comment by uvtc** [comment]
I studied physics, but never heard of tau being used for 2 pi.

**Comment by Juerd** [comment]
Most people never heard about Perl 6 in their studies. :-)

Tau, like many things in Perl 6, is a concept that is new to many people. The tau name and τ symbol have only existed for a few years. It's not surprising that you may not have heard about it ever before. But why is your lack of prior experience with this thing a reason to exclude it, given the plethora of other fancy new stuff in Perl 6, that you probably also never got taught in school? Last time I checked, Perl 6 had very little to do with maintaining the status quo.

Google does support tau in their calculator: https://www.google.nl/search?q=tau/2

**Comment by MadcapJake** [comment]
Check out the links that @Juerd added to the rakudo ticket.

Here's another one: http://www.scientificamerican.com/article/let-s-use-tau-it-s-easier-than-pi/

**Comment by moritz** [comment]
@MadcapJake IMHO as language designers, we should follow what math and physics actually do, not what somebody suggests they should do. Yes, we're supposed to innovate, but in our own domain.

**Comment by Coleoid** [comment]
Note, this isn't innovation, it's early adoption.  Earliest suggestion (that I know of) of tau as this constant is in 1988.  Younger than Perl 1, older than Perl 3.  :D  Initially it stalled, then began gaining cultural traction around 2011.

  I see τ as a number for people who enjoy mathematics, much as 'betwixt' is a word for people who enjoy English and 'unless' is a construct for people who enjoy Perl.  These symbols do no harm to the people who prefer π, 'between', and 'if not'.  Some folks prefer one over the other, some feel each choice is more expressive in some cases.
  It's controversial, though--for some reason (reasons?), plenty of folks have strong immediate convictions about this label.  Perhaps because much of the primary advocacy centers, bathwater-ishly, around pi being 'wrong'.  Or I may have the causal arrow backwards.  Or there may be more than one arrow in the causal air, here.



    On Thursday, December 3, 2015 1:03 PM, Moritz Lenz <notifications@github.com> wrote:
 

 @MadcapJake IMHO as language designers, we should follow what math and physics actually do, not what somebody suggests they should do. Yes, we're supposed to innovate, but in our own domain.—

**Comment by AlexDaniel** [comment]
I think that τ is very TIMTOWDTI-ish which fits the language. It is as basic as π is, so I don't think that it belongs to some other module.
That being said, I'm not sure if “tau” should be exported. But τ does not hurt for sure.

**Comment by ab5tract** [comment]
Another +1 for tau's inclusion. I do not find the arguments from authority
against it very convincing, but I'm not a big fan of the physics
establishment in general so that could be my own bias.

Either way this hurts nothing *and* potentially exposes people to an
interesting new mathematical question/debate. I think it is completely in
accord with Perl's philosophy. If the proof fits, tau works and can only
get more popular from here.

I don't  see any reason why Perl 6 can't be a part of that movement.

**Comment by awwaiid** [comment]
Since we're bike-shedding -- On the one hand, I feel like this should go into a lib that people can pull in. On the other ... TAU IS AWESOME and we should put it in :)

Like... then I can brag to people about Yet Another Awesome Bizzaro Thing in Perl6!

**Pull request merged**
